theme = ["hugo-cloak-email"]
baseURL = "https://h-arry-smith.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
enableEmoji = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.goldmark]
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/#cta-bottom"
    weight = -100
    pre = "ğŸ "
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -90
    pre = "ğŸ‘¨â€ğŸ’»"
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles/"
    weight = -80
    pre = "ğŸ“•"
  [[menu.main]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "/tutorials/"
    weight = -70
    pre = "ğŸ‘¨â€ğŸ«"
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = -60
    pre = "âš™ï¸"
  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = -50
    pre = "ğŸ“†"
    [[menu.main]]
    identifier = "estimate"
    name = "<span class='font-semibold text-indigo-400 transition duration-300 lg:text-4xl hover:text-indigo-500'>Get an Estimate</span>"
    url = "/estimate/"
    weight = -40